version: '3.8'

services:
  web:
    build: ./app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    networks:
      - app-network
    expose:
      - "80"  # Открываем порт внутри сети

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: