version: '3.8'

services:
  web:
    build: ./app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    networks:
      - app-network
    expose:
      - "8080"  # Изменяем порт внутри контейнера
    ports:
      - "8080:80"  # Маппинг внешнего порта 8080 на внутренний 80

  frontend:
    build: ./frontend
    ports:
      - "3001:80"  # Изменяем внешний порт с 3000 на 3001
    networks:
      - app-network
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db  # Добавляем имя базы данных
    volumes:
      - postgres_todo_data:/var/lib/postgresql/data  # Изменяем имя тома
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

networks:
  app-network:
    name: todo_network  # Даем уникальное имя сети

volumes:
  postgres_todo_data:  # Изменяем имя тома